name: setstimer
description: Interval timer.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+4 # AppStore +3, Play +3
homepage: https://timer.norr.dev

environment:
  sdk: ">=2.18.0 <3.3.0"

dependencies:
  audioplayers: ^1.0.1
  circular_countdown_timer: ^0.2.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10+5
  flutter_vibrate: ^1.3.0
  number_inc_dec: ^0.8.0
  package_info_plus: ^1.4.3+1
  path_provider: ^2.0.11
  steps_indicator: ^1.3.0
  url_launcher: ^6.1.5
  wakelock: ^0.6.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/texts/en/
    - assets/texts/ru/
    - assets/sounds/
    - CHANGELOG.md

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/Logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/Logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "assets/icon/Logo.png"
    icon_size: 48 # min:48, max:256, default: 48