name: setstimer
description: Timer for sets in powerlifting/bodybuilding/fitness.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.0+4 # AppStore +3, Play +3
homepage: https://timer.norr.dev

environment:
  sdk: ">=2.18.0 <3.3.0"

dependencies:
  audioplayers: ^1.0.1
  circular_countdown_timer: ^0.2.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.10+5
  number_inc_dec: ^0.8.0
  package_info_plus: ^1.4.3+1
  path_provider: ^2.0.11
  provider: ^6.0.3
  url_launcher: ^6.1.5
  wakelock: ^0.6.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/texts/en/
    - assets/texts/ru/
    - assets/sounds/
    - CHANGELOG.md

flutter_intl:
  enabled: true
  class_name: S
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/generated
  use_deferred_loading: false
