name: setstimer
description: Timer for sets in powerlifting/bodybuilding/fitness.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^4.3.2+2
  cupertino_icons: ^1.0.0
  circular_countdown_timer: ^0.0.7
  multiplatform_widgets:
    git: 
      url: git://github.com/filonov/multiplatform_widgets.git
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.10

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/ 
    - assets/texts/en/
    - assets/texts/ru_RU/

flutter_intl:
  enabled: true
  main_locale: en